config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  resources :accounts
  resources :assets do
  get 'return', :on => :collection
  get 'unreturn', :on => :collection
	end
  resources :withdraws, only: :index
  resources :wallets , only:[:index , :create]
  resources :banks, only:[:index , :create]
end

app/models/account.rb
class Account < ApplicationRecord
	has_many :assets
	has_many :balances
	has_many :banks
	has_many :wallets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :email, :address, :contact, presence: true

  enum receive_type: [:crypto, :aud]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
	belongs_to :account
	has_one :balance
	has_many :payouts

	scope :return_request, -> {where(return_request: true, returned_date: nil)}
	scope :active_assets, -> {where(return_request: false)}
	scope :returned_assets, -> {where.not(returned_date: nil)}
	scope :locked, -> {where(lock: true)}

	has_many :balances

	paginates_per 10

	enum status: [:waiting_delivery, :received, :active, :returned]

	validates :name, :model, :memory, presence: true

end

app/models/balance.rb
class Balance < ApplicationRecord
	belongs_to :asset
	belongs_to :account
	scope :unreturned_assets, -> {joins(:asset).where(assets: { return_request: false})}
	scope :returned_assets, -> {joins(:asset).where(assets: { return_request: true})}
end

app/models/bank.rb
class Bank < ApplicationRecord
	belongs_to :account
	paginates_per 10

	validates :name, :bsb, :account_number, :amount, presence: true

	scope :confirmed, -> {where(confirm: true)}
	scope :unconfirmed, -> {where(confirm: false)}
end

app/models/payout.rb
class Payout < ApplicationRecord
  belongs_to :asset
end

app/models/wallet.rb
class Wallet < ApplicationRecord
	belongs_to :account
	paginates_per 10

	validates :address, :date, :amount, presence: true
	 validates_format_of :address, :with => /^0x[a-fA-F0-9]{40}$/, :multiline => true, :on => :create

	scope :confirmed, -> {where(confirm: true)}
	scope :unconfirmed, -> {where(confirm: false)}
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

	before_action :authenticate_account!, only:[:new,:create]

	def index
		@assets = Asset.where(account_id: current_account.id).order("created_at DESC").paginate(page: params[:page], per_page: 10)
		@total_wallet = Balance.where(account_id: current_account.id).sum("crypto_amount")
	end

	def create
		@asset = current_account.assets.create(asset_params)
		if @asset.valid?
			#binding.pry
			Balance.create(asset_id: @asset.id, account_id: @asset.account_id)
			redirect_to assets_path
		else
			flash[:alert] = "Invalid input"
			render :index,status: :unprocessable_entity
		end
	end

	def edit
		@asset = Asset.find(params[:id])
		if @asset.lock
			redirect_to assets_path
			flash[:alert] = "You cannot edit the locked assets "
		end
	end

	def update
		@asset = Asset.find(params[:id])
		if @asset.update(asset_params)
			redirect_to assets_path
		else
			redirect_to edit_asset_path
		end
	end


	def return
		binding.pry
		Asset.where(id: params[:id]).update(return_request: true , return_request_date: Date.today, return_request_address: params[:return_request_address])
		#@asset = Asset.find(params[:id])
		#AssetMailer.request_asset(@asset).deliver

		redirect_to assets_path
	end

	def unreturn
		Asset.where(id: params[:id]).update(return_request: false)
		#@asset = Asset.find(params[:id])
		#AssetMailer.unreturn_request_asset(@asset).deliver
		redirect_to assets_path
	end

	private
	def asset_params
		params.require(:asset).permit(:account_id,:name,:make,:model,:memory,:serial_number,:description)
	end

	#def update_params
		#params.require(:asset).permit(:requet_return, ret_date: Date)
	#end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :authenticate_account!

	def create
		@banks = current_account.banks.create(bank_params)
		if @banks.valid?
			redirect_to withdraws_path
		else
			redirect_to withdraws_path
      flash[:alert] = "Please fill up all fields"
		end

	end
	private
	def bank_params
    total_bank = Balance.where(account_id: current_account.id).sum("aud_amount")
    #binding.pry
		params.require(:bank).permit(:account_id,:name,:bsb,:account_number).merge(amount: total_bank)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
	before_action :authenticate_account!

	def create
			@wallets = current_account.wallets.create(wallet_params)
			if @wallets.valid?
				redirect_to withdraws_path
			else
				redirect_to withdraws_path
				flash[:alert] = "Please enter valid wallet address"
			end
		end

	private
	def wallet_params
		total_wallet = Balance.where(account_id: current_account.id).sum("crypto_amount")
		params.require(:wallet).permit(:account_id,:address,:date).merge(amount: total_wallet)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mining Hub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Dosis|Open+Sans" rel="stylesheet">
    <!-- Bootstrap core CSS -->
        <link href="https://blackrockdigital.github.io/startbootstrap-creative/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-creative/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-creative/vendor/magnific-popup/magnific-popup.csss" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-creative/css/creative.min.csss" rel="stylesheet">

    <!-- Bootstrap core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-creative/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-creative/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </head>

  <body>
    <div id="wrapper">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash_messages' %>
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>

  <!-- Plugin JavaScript -->
  <script src="https://blackrockdigital.github.io/startbootstrap-creative/vendor/jquery-easing/jquery.easing.min.js"></script>
  <script src="https://blackrockdigital.github.io/startbootstrap-creative/vendor/scrollreveal/scrollreveal.min.js"></script>
  <script src="https://blackrockdigital.github.io/startbootstrap-creative/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="https://blackrockdigital.github.io/startbootstrap-creative/js/creative.min.js"></script>

</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center" style="margin-top: 70px;"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center" style="margin-top: 70px;"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center" style="margin-top: 70px;"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer text-center">
	<div class="container">
	<p>© Mining Hub <%=Date.today.year %> All Rights Reserverd</p>
	</div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">  <%= link_to 'Mining Hub' , root_path, class:'navbar-brand' %></a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto pull-right">
        <% if account_signed_in? %>
          <li class="nav-item"><%= link_to 'Assets' , assets_path, class:"nav-link js-scroll-trigger " %></li>
          <li class="nav-item"><%= link_to 'Payouts' , withdraws_path, class:"nav-link js-scroll-trigger " %></li>
          <li class="nav-item"><%= link_to 'Edit Profile' , edit_account_registration_path, class:"nav-link js-scroll-trigger " %></li>
          <li class="nav-item"><%= link_to 'Log Out', destroy_account_session_path, class:"nav-link js-scroll-trigger", method: :delete %></li>
          <% else %>
           <li class="nav-item"><%= link_to 'Home', root_path, class:"nav-link js-scroll-trigger pull-right"  %></li>
            <li class="nav-item"><%= link_to 'Sign Up', new_account_registration_path, class:"nav-link js-scroll-trigger " %></li>
            <li class="nav-item"><%= link_to 'Log In', new_account_session_path, class:"nav-link js-scroll-trigger " %></li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>