config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  resources :accounts
  resources :assets do
  get 'return', :on => :collection
  get 'unreturn', :on => :collection
	end
  resources :withdraws, only: :index
  resources :wallets , only:[:index , :create]
  resources :banks, only:[:index , :create]
end

app/models/account.rb
class Account < ApplicationRecord
	has_many :assets
	has_many :balances
	has_many :banks
	has_many :wallets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :email, :address, :contact, presence: true

  enum receive_type: [:crypto, :aud]

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
	belongs_to :account
	has_one :balance
	has_many :payouts

	scope :return_request, -> {where(return_request: true, returned_date: nil)}
	scope :active_assets, -> {where(return_request: false)}
	scope :returned_assets, -> {where.not(returned_date: nil)}
	scope :locked, -> {where(lock: true)}

	has_many :balances

	paginates_per 10

	enum status: [:waiting_delivery, :received, :active, :returned]

	validates :name, :model, :memory, presence: true

end

app/models/balance.rb
class Balance < ApplicationRecord
	belongs_to :asset
	belongs_to :account
	scope :unreturned_assets, -> {joins(:asset).where(assets: { return_request: false})}
	scope :returned_assets, -> {joins(:asset).where(assets: { return_request: true})}
end

app/models/bank.rb
class Bank < ApplicationRecord
	belongs_to :account
	paginates_per 10

	validates :name, :bsb, :account_number, :amount, presence: true

	scope :confirmed, -> {where(confirm: true)}
	scope :unconfirmed, -> {where(confirm: false)}
end

app/models/payout.rb
class Payout < ApplicationRecord
  belongs_to :asset
end

app/models/wallet.rb
class Wallet < ApplicationRecord
	belongs_to :account
	paginates_per 10

	validates :address, :date, :amount, presence: true
	 validates_format_of :address, :with => /^0x[a-fA-F0-9]{40}$/, :multiline => true, :on => :create

	scope :confirmed, -> {where(confirm: true)}
	scope :unconfirmed, -> {where(confirm: false)}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

	before_action :authenticate_account!, only:[:new,:create]

	def index
		@assets = Asset.where(account_id: current_account.id).order("created_at DESC").paginate(page: params[:page], per_page: 10)
		@total_wallet = Balance.where(account_id: current_account.id).sum("crypto_amount")
	end

	def create
		@asset = current_account.assets.create(asset_params)
		if @asset.valid?
			#binding.pry
			Balance.create(asset_id: @asset.id, account_id: @asset.account_id)
			redirect_to assets_path
		else
			flash[:alert] = "Invalid input"
			render :index,status: :unprocessable_entity
		end
	end

	def edit
		@asset = Asset.find(params[:id])
		if @asset.lock
			redirect_to assets_path
			flash[:alert] = "You cannot edit the locked assets "
		end
	end

	def update
		@asset = Asset.find(params[:id])
		if @asset.update(asset_params)
			redirect_to assets_path
		else
			redirect_to edit_asset_path
		end
	end


	def return
		binding.pry
		Asset.where(id: params[:id]).update(return_request: true , return_request_date: Date.today, return_request_address: params[:return_request_address])
		#@asset = Asset.find(params[:id])
		#AssetMailer.request_asset(@asset).deliver

		redirect_to assets_path
	end

	def unreturn
		Asset.where(id: params[:id]).update(return_request: false)
		#@asset = Asset.find(params[:id])
		#AssetMailer.unreturn_request_asset(@asset).deliver
		redirect_to assets_path
	end

	private
	def asset_params
		params.require(:asset).permit(:account_id,:name,:make,:model,:memory,:serial_number,:description)
	end

	#def update_params
		#params.require(:asset).permit(:requet_return, ret_date: Date)
	#end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
	before_action :authenticate_account!
	def create
		@balances = current_account.balances.create(balance_params)
	end
	
	private
	def balance_params
		params.require(:balance).permit(:asset_id,:crypto_name,:crypto_amount,:payout_date)
	end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :authenticate_account!

	def create
		@banks = current_account.banks.create(bank_params)
		if @banks.valid?
			redirect_to withdraws_path
		else
			redirect_to withdraws_path
      flash[:alert] = "Please fill up all fields"
		end

	end
	private
	def bank_params
    total_bank = Balance.where(account_id: current_account.id).sum("aud_amount")
    #binding.pry
		params.require(:bank).permit(:account_id,:name,:bsb,:account_number).merge(amount: total_bank)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
	before_action :authenticate_account!

	def create
			@wallets = current_account.wallets.create(wallet_params)
			if @wallets.valid?
				redirect_to withdraws_path
			else
				redirect_to withdraws_path
				flash[:alert] = "Please enter valid wallet address"
			end
		end

	private
	def wallet_params
		total_wallet = Balance.where(account_id: current_account.id).sum("crypto_amount")
		params.require(:wallet).permit(:account_id,:address,:date).merge(amount: total_wallet)
	end
end

app/controllers/withdraws_controller.rb
class WithdrawsController < ApplicationController
	before_action :authenticate_account!
	def index
		#@method = current_account.receive_type
		@wallet = Wallet.where(account_id: current_account.id).last
		#@banks = Bank.where(account_id: current_account.id).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
		#@total_bank_withdraw = Bank.where(account_id: current_account.id, confirm: true).sum("amount")
		#@total_wallet_withdraw = Wallet.where(account_id: current_account.id, confirm: true).sum("amount")
		@assets = Asset.where(account_id: current_account.id)
		@payouts = Payout.where(asset_id: current_account.assets.ids).order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
		@total_payouts = Payout.where(asset_id: current_account.assets.ids).sum("payout_amount")
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/helpers/withdraws_helper.rb
module WithdrawsHelper
end

app/views/accounts/index.html.erb
<h1>Hello</h1>

app/views/assets/edit.html.erb
<div class="container" style="margin-top:100px;">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Edit your account</h3>
        </div>
          <div class="panel-body">
<%= simple_form_for @asset , method: :patch do |f| %>
        <%= f.input :name %>
        <%= f.input :make %>
        <%= f.input :model %>
        <%= f.input :memory %>
        <%= f.input :serial_number %>
        <%= f.input :description %>
        <%= f.submit 'Submit' , class: 'btn btn-primary'  %>
 <% end %>
 </div>
 </div>
 </div>
 </div>
 </div>

app/views/assets/index.html.erb
<div class="container" style="margin-top: 100px">
  <button type="button" class="btn btn-primary btn-lg btn_idea pull-right" data-toggle="modal" data-target="#myModal">
  <span class="glyphicon glyphicon-plus"></span> &nbsp;Add Asset
</button>
<br><br><br>

<div>
  <!-- <p><b>Total Amount in AUD:</b>  $ <%= @total_bank %></p> -->
  <p><b>Total Amount in CRYPTO:</b> <%= @total_wallet %> ETH</p>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for Asset.new do |f| %>
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Add your Asset</h4>
      </div>
      <div class="modal-body">

        <%= f.input :name %>
        <%= f.input :make %>
        <%= f.input :model %>
        <%= f.input :memory, collection: ["4GB", "8GB", "16GB", "32GB", "64GB"], include_blank: false %>
        <%= f.input :description %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>




<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Make</th>
        <th>Model</th>
        <th>Memory</th>
        <th>Hash Rate</th>
        <th>Status</th>
        <th>ETH Balance</th>
      </tr>
    </thead>

  <% @assets.each do|asset| %>
      <tbody>
        <% if asset.return_request %>
      <tr style="background:orange">
        <td><%= asset.name %></td>
        <td><%= asset.make %></td>
        <td><%= asset.model %></td>
        <td><%= asset.memory %></td>
        <td><%= asset.hash_rate %></td>
        <td><%
        if asset.status == "active"
          concat "Active & Mining"
        end
        if asset.status == "waiting_delivery"
          concat "Waiting Delivery"
        end
        if asset.status == "received"
          concat "Received and Testing"
        end
        if asset.status == "returned"
          concat "Returned"
        end
        %></td>
        <td><%= asset.balance.crypto_amount %></td>
        <% if !asset.return_request %>
        <td><%= link_to 'Return' , return_assets_path(id: asset.id), class: 'btn btn-sm btn-success', data: {toggle:"modal"}, href:"#returnModal" %></td>
        <% else %>
        <td>
          <% if asset.status != 'returned' %>
            <%= link_to 'Cancel Return' , unreturn_assets_path(id: asset.id), class: 'btn btn-sm btn-primary' %> </td>
          <% end %>
         <% end %>
         <% if !asset.lock || asset.status == " waiting_ delivery" %>
        <td><%= link_to 'Edit' , edit_asset_path(id: asset.id), class: 'btn btn-sm btn-primary' %> </td>
        <% end %>
      </tr>
      <% else %>
      <tr>
        <td><%= asset.name %></td>
        <td><%= asset.make %></td>
        <td><%= asset.model %></td>
        <td><%= asset.memory %></td>
        <td><%= asset.hash_rate %></td>
        <td><%
        if asset.status == "active"
          concat "Active & Mining"
        end
        if asset.status == "waiting_delivery"
          concat "Waiting Delivery"
        end
        if asset.status == "received"
          concat "Received and Testing"
        end
        if asset.status == "returned"
          concat "Returned"
        end
         %></td>
        <td><%= asset.balance.crypto_amount %></td>
        <td><% if asset.status != "waiting_delivery" %>
          <% if !asset.return_request %>
          <button class='btn btn-sm btn-success' data-toggle="modal" data-target="#returnModal">Return</button>
          <div class="modal fade" id="returnModal" tabindex="-1" role="dialog" aria-labelledby="returnModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h4 class="modal-title" id="returnModalLabel">Please enter the address you want to return the asset.</h4>
                </div>
                <div class="modal-body">
                  <form action="<%= return_assets_path %>" method="get">
                    <input type="hidden" name="id" value="<%= asset.id %>">
                    <input type="text" name="return_request_address" class="form-control text required" required />
                </div>
                <div class="modal-footer">
                  <input type="submit" class='btn btn-sm btn-success' value="Return" />
                </form>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
          <% else %>
          <%= link_to 'Cancel Return' , unreturn_assets_path(id: asset.id), class: 'btn btn-sm btn-primary' %>
           <% end %>
         <% end %></td>
         <% if !asset.lock || asset.status == " waiting_ delivery" %>
        <td><%= link_to 'Edit' , edit_asset_path(id: asset.id), class: 'btn btn-sm btn-primary' %> </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
   <% end %>
 </table>
 </div>
 <div class="text-center">
    <%= will_paginate @assets %>
  </div>
</div>